### ISSUE TITLE
Grain (Paddy) Detect from Image

### ISSUE THREAD

**Issue by sumit1212** [deepakrana47/Wheat-quality-detector-2#3]
### Detect Paddy in Image 
![1](https://user-images.githubusercontent.com/28036324/66456062-352c6880-ea8a-11e9-8cfd-8696ce0eef18.jpg)

> Count the number of paddy in a image.
> I have create a Model to detect paddy using **Tensorflow API Object detection** model but it did not work properly, can please help me out how to do that.
> I have learn a lot from your example i.e. Wheat-quality-detector.
> Please tell which approach are you using  and technology and some tutorial and blog are you have pls suggest.

**When Run python cmd_wheat_quality_detector_v2.py**

> It will give me error : 

`Using TensorFlow backend.
2019-10-09 10:43:05.765390: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3092785000 Hz
2019-10-09 10:43:05.765957: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555efc684df0 executing computations on platform Host. Devices:
2019-10-09 10:43:05.765992: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Enter the file(wheat image) location to dectect : mark.jpg
Traceback (most recent call last):
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/engine/saving.py", line 382, in _deserialize_model
    model.optimizer.set_weights(optimizer_weight_values)
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/optimizers.py", line 126, in set_weights
    'of the optimizer (' + str(len(params)) + ')')
ValueError: Length of the specified weight list (13) does not match the number of weights of the optimizer (19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cmd_wheat_quality_detector_v2.py", line 20, in <module>
    model = keras.models.load_model('weights_results_5out/weights_01234567.pkl')
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/engine/saving.py", line 384, in _deserialize_model
    warnings.warn('Error in loading the saved optimizer '
UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
`
**Thank You**

> Detect single paddy from image :

![Screenshot from 2019-10-09 15-00-37](https://user-images.githubusercontent.com/28036324/66469601-c2c98180-eaa5-11e9-9c96-8b07e74cfee3.png)

> >How to count number of paddy in image:

![Screenshot from 2019-10-09 15-01-09](https://user-images.githubusercontent.com/28036324/66469675-e4c30400-eaa5-11e9-915a-a92fc1e871e8.png)

**Comment by deepakrana47** [comment]
1. For python, have you tried the code (cmd_wheat_quality_detector_v2.py) with the  packages specified in *Readme** with their specific versions?

2. I had done the segmentation of wheat in [git link](https://github.com/deepakrana47/segmentation-of-wheat-connected-in-a-picture) and [paper](https://www.ijeecse.com/V5N1-023.pdf) explain the approach, but in you case you have to come up on you own with the method that works for you.

**Comment by sumit1212** [comment]
**No not work properly** 
**yes, I have try to run this file but that give me error i. e. also mention. what I do**

` python cmd_wheat_quality_detector_v2.py 
Using TensorFlow backend.
2019-10-09 18:03:22.225365: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3092785000 Hz
2019-10-09 18:03:22.225854: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55aa44d05ea0 executing computations on platform Host. Devices:
2019-10-09 18:03:22.225912: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Enter the file(wheat image) location to dectect : mark.jpg
Traceback (most recent call last):
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/engine/saving.py", line 382, in _deserialize_model
    model.optimizer.set_weights(optimizer_weight_values)
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/optimizers.py", line 126, in set_weights
    'of the optimizer (' + str(len(params)) + ')')
ValueError: Length of the specified weight list (13) does not match the number of weights of the optimizer (19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cmd_wheat_quality_detector_v2.py", line 20, in <module>
    model = keras.models.load_model('weights_results_5out/weights_01234567.pkl')
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/media1/miniconda3/envs/test_env_36/lib/python3.6/site-packages/keras/engine/saving.py", line 384, in _deserialize_model
    warnings.warn('Error in loading the saved optimizer '
UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
`

**Comment by deepakrana47** [comment]
I am asking have you run the code while after installing the following requirements(**given in Readme**)
 python==2.7
 numpy==1.15.4
 opencv==3.4.0.12
 Keras==2.1.2

**Comment by sumit1212** [comment]
**No, I'm using these version of lib**

> python == 3.6
> numpy == 1.8.2
> opencv == 4.1
> keras == 2.1.2

**Comment by deepakrana47** [comment]
Try to run the code with the following requirements.
python==2.7
numpy==1.15.4
opencv==3.4.0.12
Keras==2.1.2
