### ISSUE TITLE
Unable to use python 2.7

### ISSUE THREAD

**Issue by Sunil-430** [deepakrana47/Wheat-quality-detector-2#4]
I am unable to use python 2.7 in anaconda.  Can you just help me out to execute the code that you have written in python 3.7? I am unable to load the segmented data. Explain to me the approach that I have to adopt.

**Comment by deepakrana47** [comment]
The approach I had used is explained in the following line [https://github.com/dhishku/Machine-Learning-for-Grain-Assaying/blob/master/interim_project_report.pdf].

**Comment by Sunil-430** [comment]
Thank you for updating the respiratory in python 3. 
But still, I am facing the same issue. I am getting the error like this

Traceback (most recent call last):
  File "C:/Users/Kaluram ji/PycharmProjects/MY_majorproject-11/Wheat-quality-detector-2-master/segment_formation_v6.py", line 15, in <module>
    model = keras.models.load_model(mFile)
  File "C:\Users\Kaluram ji\Anaconda3\envs\PycharmProjects\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\Users\Kaluram ji\Anaconda3\envs\PycharmProjects\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "C:\Users\Kaluram ji\Anaconda3\envs\PycharmProjects\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\Kaluram ji\Anaconda3\envs\PycharmProjects\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "C:\Users\Kaluram ji\Anaconda3\envs\PycharmProjects\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "C:\Users\Kaluram ji\Anaconda3\envs\PycharmProjects\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 254, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'

Process finished with exit code 1

**Comment by Sunil-430** [comment]
I am confused... Is it because of the editor that I am(pycharm) using?

**Comment by deepakrana47** [comment]
hi @Sunil-430 , I had updated the repo for python3. So, check it out
the requirment are also updated. If still facing the problem let me know.

**Comment by Sunil-430** [comment]
Thank you **@deepakrana47**... It worked
